### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by mdsumner** [diminutive/idea.sources00#1]
- [ ] name this properly, and move it
- [x] construct DSN so that GDAL will read the HDF without cruft
- [ ] python examples
- [ ] do something interesting
- [ ] make this part of *sources*?
